### ISSUE TITLE
Results list sometimes populates with items that do not match query

### ISSUE THREAD

**Issue by JahBrewski** [guylabs/ion-autocomplete#41] opened 2015-06-30 23:16 UTC
I'm using a static array to populate the directive using the items-method. However, sometimes, the results list will populate with list items that don't match my query. However, when one of these results is clicked, they will change to a result that does match. See these screenshots:
![Before clicked](https://cloud.githubusercontent.com/assets/2348386/8444181/9b9ef12a-1f53-11e5-8e82-0703919e311d.png)

![After clicked](https://cloud.githubusercontent.com/assets/2348386/8444186/a832888e-1f53-11e5-909f-bc1928cad542.png)

Here is what my controller looks like:

```javascript

  find = function(key, array) {
    var results = [];
    for (var i = 0; i < array.length; i++) {
      if (array[i].search(new RegExp(key, "i")) != -1) {
        results.push(array[i]);
      }
    }
    return results;
  }

  $scope.featuresList = function(query) {
    return find(query, $scope.propertyFieldOptions.exteriorFeatures);
  }
```

And my html:

```html
<ion-autocomplete ng-model="property.exterior_features" items-method="featuresList(query)" multiple-select="true" placeholder="Enter exterior features..." class="text-right"/>

**Comment by guylabs** [comment] 2015-07-01 05:29
Hi Joel,

ok that looks strange. Could you maybe create a small sample with the https://github.com/guylabs/ion-autocomplete/blob/master/test/e2e/ion-autocomplete.multiple-select.e2e.html html template where this issue is reproducible? Do you also get this error when you do not call your `find` function and return a hardcoded array (as it is done in the `ion-autocomplete.multiple-select.e2e.html` template) instead? 

Please also have a look at https://github.com/guylabs/ion-autocomplete#the-item-value-key and https://github.com/guylabs/ion-autocomplete#the-item-view-value-key options to be able to set the proper model and view of the items. 

I just need some kind of reproducible template, because I never saw this kind of issue.

Thanks and regards,

Guy

**Comment by guylabs** [comment] 2015-07-24 10:44
Hi Joel,

any news on this?

Thanks and regards,

Guy

**Comment by guylabs** [comment] 2015-08-13 05:05
Hi Joel,

I will close the issue now. If you have any news on this please reopen it.

Thanks and regards,

Guy

**Closed by guylabs** 2015-08-13 05:05 UTC
Labels: question
