### ISSUE TITLE
$http promise not working

### ISSUE THREAD

**Issue by itree** [guylabs/ion-autocomplete#27] opened 2015-06-04 17:01 UTC
calling remote data seems to be not working.  

$scope.callbackMethod = function (query) {
    return $http.get(endpoint);
}
 
on the server side, I can see that the request is hitting the server, but not completing. 

Let me know if I'm missing something.

**Comment by guylabs** [comment] 2015-06-04 21:11
Hi,

what do you mean with not completing? Can you have a look at the example which I use for the end to end tests here: https://github.com/guylabs/ion-autocomplete/blob/master/test/e2e/ion-autocomplete.single-select.e2e.html

There the component is properly defined. Please also have a look at the `items-method-value-key` property in the documentation (https://github.com/guylabs/ion-autocomplete#the-items-method-value-key). As this property is important for the response.

Could you maybe also post the component configuration and a sample response? Or just try to implement it with the test html.

Thanks and regards,

Guy

**Comment by itree** [comment] 2015-06-04 21:58
Hey Guy,  

I was able to make it work with local data source much like what you have in your example.  The problem comes when I try to get remote source using $http as a promise.  


What I mean 'not completing' is that I can see in the log that server script is being hit, but it never runs.  I know it is very strange.  I even created a server script where there is only one line.  And it doesn't run.  And no errors is being emitted on the server or client side.  

I have seen this error before in AngularJS related to Access-Control-Allow-Origin", '*' 

I'm going to make a fresh project and try again.  I'm bit exhausted now.  Will let you know.

**Comment by guylabs** [comment] 2015-06-04 22:01
Ok good. Well I also use a wrapped `$http.get()` call and return a promise in the `items-method` and this works properly. Did you check that the remote response has the proper format? I would just modify the test html at first to use a `$http.get()` call and if this is not working please send me your html and then I can have a look.

**Comment by itree** [comment] 2015-06-06 15:04
Ok Guy, 

I took another stab at this with a fresh mind. I got some where:


Ok here is what I have in the html
<ion-autocomplete 
  ng-model="model" 
  multiple-select="false" 
  items-method="getAddresses(query)"  
  items-clicked-method="addressClicked(callback)"  
  item-value-key="id" 
  cancel-label="Done"
  select-items-label="Select..." 
  selected-items-label="Selected:" 
  placeholder="Search...."
/>
Notice that I am NOT setting items-method-value-key, because I'm returning an array. 

This is what the array looks like:
  $scope.getAddresses = function(query){
    return [
    {"name":"Smith", "id":"1"},
    {"name":"John", "id":"2"},    
    ];
}

This works:
if I try to get remote:
    return $http.get('http://locahost:8080/get.address', {params: {term : query}    });
------
It is returning the same thing:
[
    {"name":"Smith", "id":"1"},
    {"name":"John", "id":"2"},    
    ]
I get this in the console log

[phonegap] [console.log] http://192.168.0.12:8081/spacebook/p/ax.address.bookhdhgf
[phonegap] [console.error] Error: collection-repeat expected an array for 'items', but got a undefined
[phonegap]     at http://192.168.0.12:3000/lib/ionic/js/ionic.bundle.js:50421:15
[phonegap]     at Object.$watchCollectionAction [as fn] (http://192.168.0.12:3000/lib/ionic/js/ionic.bundle.js:22809:13)
[phonegap]     at Scope.$digest (http://192.168.0.12:3000/lib/ionic/js/ionic.bundle.js:22942:29)
[phonegap]     at Scope.$apply (http://192.168.0.12:3000/lib/ionic/js/ionic.bundle.js:23205:24)
[phonegap]     at done (http://192.168.0.12:3000/lib/ionic/js/ionic.bundle.js:18358:47)
[phonegap]     at completeRequest (http://192.168.0.12:3000/lib/ionic/js/ionic.bundle.js:18548:7)
[phonegap]     at XMLHttpRequest.requestLoaded (http://192.168.0.12:3000/lib/ionic/js/ionic.bundle.js:18489:9)
[phonegap] 200 /__api__/autoreload

looks like when it is remote it is automatically looking for "items" as the items-method-value-key. 

Is there any way we can not do that, because the remote data is already preset to use for other services and it always returns as an array. It would be good if the $http and locadata act the same way.

**Comment by guylabs** [comment] 2015-06-07 16:33
Hi,

I just had a look and I cannot reproduce it. Could you maybe add the following block of code:
```javascript
console.log(promiseData);
console.log(compiledTemplate.scope.itemsMethodValueKey);
var processedItems = compiledTemplate.scope.getItemValue(promiseData, compiledTemplate.scope.itemsMethodValueKey);
console.log(processedItems);
```
to the following line: https://github.com/guylabs/ion-autocomplete/blob/master/src/ion-autocomplete.js#L173 ? You can just edit the `ion-autocomplete.js` file in your project and then attach the log output here?

That would be great!

Thanks and regards,

Guy

**Comment by umadesign** [comment] 2015-06-07 18:15
Hi, I was having the same problem. After following Guy's advice and debugging ion-autocomplete.js I think I spotted the problem. You need to make sure your callback returns the **promised data** instead of the promise. I'm a complete angularjs newbie, so maybe this is not the right way to do it, but it seemed to have solved the problem:

```javascript
$scope.termSearch = function(query) {

	var url = 'your_base_url';

	return $http.get( url + "?term=" + query )

	  .success(function(data, status, headers, config) {
	    // this callback will be called asynchronously
	    // when the response is available

	    return data;

	  })

	  .error(function(data, status, headers, config) {
	    // called asynchronously if an error occurs
	    // or server returns response with an error status.

	  }).then(function(resp){
	  	// this is where you actually define the data being returned
	  	
	  	return resp.data;

	  });

}
````
Hope it helps! 

Paulo Cruz

**Comment by guylabs** [comment] 2015-06-08 05:37
Hi Paulo,

thanks for your post and now I see the issue. I always used the `SpringDataRestProvider` from my other project (https://github.com/guylabs/angular-spring-data-rest) and there the data returned in the promise is right away the correct one. But in a `$http.get()` response the data is stored in the `response.data` object as you showed in the example.

I will add a fix for that in the `0.2.3` release.

Thanks for catching it!

Regards,

Guy

**Comment by umadesign** [comment] 2015-06-08 09:19
Hi Guy, you're welcome! Thank you for the great work! Regards

**Comment by guylabs** [comment] 2015-06-08 20:06
Ok I just added the fix to the master. Can you please test the latest master that it works without the workaround from Paulo? If it works I am able to close the issue.

Thanks and regards,

Guy

**Comment by guylabs** [comment] 2015-06-14 15:40
Hi,

any news on this?

Thanks and regards,

Guy

**Comment by itree** [comment] 2015-06-14 18:08
Hey Guy,  thanks for checking in.  I'm reorganizing my code base a bit and the code base, I haven't had time to check.   I'll take a look again later today.  Thanks for making the quick feedback, btw.

**Comment by nuba** [comment] 2015-06-16 23:12
@umadesign with a $http response like this

```
{
  "data": {
      "people": [
          {"id":1, "name":"alice"},
          {"id":2, "name":"bob"}
      ]
  }
}
```

you can use

```xml
<ion-autocomplete ng-model="user"
 items-method="ionAutocompleteCallback(query, componentId)"
 items-method-value-key="data.people"
/>
```

meaning you can stick to

```javascript
return $http.get(
// your request details
);
```

if you want :)

**Comment by guylabs** [comment] 2015-06-24 20:06
@itree Any news on this?

**Comment by guylabs** [comment] 2015-07-01 06:49
Closing the issue because of inactivity.

**Closed by guylabs** 2015-07-01 06:49 UTC
Labels: bug
