### ISSUE TITLE
remove the default text on selected items and select

### ISSUE THREAD

**Issue by vvavepacket** [guylabs/ion-autocomplete#183] opened 2016-06-13 01:15 UTC
Hi, quick question. How do we remove the 'selected item' and 'select an item' similar below?

![remove](https://cloud.githubusercontent.com/assets/8295642/15995082/b1ff3c30-30e2-11e6-9f7c-632cef095d91.PNG)

Thank you.

**Comment by guylabs** [comment] 2016-06-21 17:05
Hi @vvavepacket,

this is a duplicate of #172. Please follow this issue as this is already an enhancement and is planned to be implemented.

I will close this now as duplicate.

Thanks and regards,

Guy

**Closed by guylabs** 2016-06-21 17:05 UTC
Labels: duplicate

**Comment by guylabs** [comment] 2016-10-27 06:27
Hi @vvavepacket 

the easiest way is to create a own custom template where you do not have these two `ion-item` defined. You can have a look at this here: https://github.com/guylabs/ion-autocomplete#template-url

Therefore I will close this issue as this is the way to go. Adding a custom functionality just blows up the codebase.

Thanks and regards,

Guy
