### ISSUE TITLE
Backdrop randomly doesn't hide

### ISSUE THREAD

**Issue by Vahn84** [guylabs/ion-autocomplete#55] opened 2015-07-24 10:38 UTC
As the title

The backdrop that appears behind the search popup sometimes doesn't hide when i click the done or the cancel button, and it's required to tap the back button of the phone to make it go away

**Comment by guylabs** [comment] 2015-07-24 11:00
Hi Fabio,

hmm strange I never had this issue with the Cancel/Done button. Because we call the same method here https://github.com/guylabs/ion-autocomplete/blob/master/src/ion-autocomplete.js#L325 as we do when the back button is pressed on the phone.

You do not have a way to reproduce it right? And does it happen often or just when you open the dialog and then immediately close it again?

Thanks and regards,

Guy

**Comment by Vahn84** [comment] 2015-07-24 11:26
Hi Guy!

Lost a bunch of minutes trying to reproduce the issue. 

It seems that backdrop doesn't hide (sometimes) only when inspecting the app with the chrome developer tools. My fault :( ...but i didn't think it could have been THE problem

**Comment by guylabs** [comment] 2015-07-24 11:36
Ok maybe that could have been the issue. If you once again find it on the phone or somewhere else then please reopen it and we can have a look at it.

Thanks.

**Comment by goneale** [comment] 2015-08-28 04:59
Hi guys,
This issue still seems to be occurring, It seems to occur on both with and without chrome dev tools being open. I've just taken a video of the behavior before I found this issue which I have attached.

Any ideas?
Cheers
![strange-behaviour](https://cloud.githubusercontent.com/assets/107109/9539473/60f91c74-4d95-11e5-8cdb-e1b55e9123f0.gif)

**Comment by guylabs** [comment] 2015-08-28 05:43
Hi Graham,

ok that is annoying. Currently I am in the process of upgrading to Ionic 1.1.0 and there I need to do a lot of changes and when this still happens there I will have a look at it. As I never had this problem locally. Maybe it is because you have a full app and not just a test case as I have.

I hope that its ok for you for now. You will get notified when the new version is out.

Thanks and regards,

Guy

**Comment by goneale** [comment] 2015-08-28 05:48
Yeah, sorry to raise issues from the dead :) For now I will try and find a work-around, even if I hide the backdrop somehow manually.
Good luck and appreciate all the free time you put into the project.

**Comment by goneale** [comment] 2015-08-28 07:22
I would probably look at increasing your `searchInputElement[0].focus();` setTimeout to 100ms from 0ms, it seems to be more reliable. at 0, it still intermittently doesn't focus I found, particularly on page reloads from cache.

**Comment by guylabs** [comment] 2015-08-28 08:56
Ok thanks. I just fixed it in https://github.com/guylabs/ion-autocomplete/commit/0e2a648fd8c56b9f6e6819755b9fe6827a63db39.

**Comment by guylabs** [comment] 2015-09-05 06:17
Hi Graham,

could you maybe test the `0.3.0` version or right away the latest master to see if this still happens?

Thanks and regards,

Guy

**Comment by SatadruBhattacharjee** [comment] 2015-09-14 07:05
I was also facing the exact same problem, specially on low end Android Devises, where I can reproduce this 4 times out of 5 time.

With ionic 1.1.0 and 0.3.0 update, the issue is FIXED , Kudos to you

**Comment by guylabs** [comment] 2015-09-14 07:46
Hi Satadru,

thanks for testing it and nice that it is fixed now :).

Regards,

Guy

**Closed by guylabs** 2015-09-14 07:46 UTC
Labels: bug

**Comment by goneale** [comment] 2015-09-14 12:15
Hi Guy, could you update the bower package to the latest for this as well? Thanks again for fixing this.

**Comment by guylabs** [comment] 2015-09-17 20:14
Hi Graham,

yes I will update and release the `0.3.1` version asap when the other issues are fixed. Till then you can use the master. You can read it here how to do this: http://guylabs.ch/2015/05/08/get-latest-master-changes-of-a-bower-dependency

Thanks and regards,

Guy
