### ISSUE TITLE
Feature Request: Display all items if query is empty

### ISSUE THREAD

**Issue by taybin** [guylabs/ion-autocomplete#38] opened 2015-06-25 17:24 UTC
When the query is empty, I'd like to display the full set of items.

**Comment by guylabs** [comment] 2015-06-25 18:35
Hi Taybin,

you need to implement the proper `itemsMethod` which returns all items when the passed in `query` is empty. You can read more about the `itemsMethod` here: https://github.com/guylabs/ion-autocomplete#the-items-method.

Or do you mean that the component does a call to the `itemsMethod` with the empty query when the dialog opens such that you already have a list before entering something? This way you also need to implement what I wrote in the first paragraph, but the behavior is different when the dialog opens.

Please let me know what exactly you mean.

Thanks and regards,

Guy

**Comment by taybin** [comment] 2015-06-25 19:08
According to this (https://github.com/guylabs/ion-autocomplete/blob/master/src/ion-autocomplete.js#L172), it short-circuits the searchQuery $watch handler if the query is empty.  I don't see any way to get the component to call the itemsMethod handler with an empty query.

**Comment by JahBrewski** [comment] 2015-06-30 01:35
I am also trying to accomplish this. Is it currently possible?

**Comment by guylabs** [comment] 2015-06-30 05:05
I tried to change the behavior but there are some failing tests which I need to fix. I hope I can finish it till the weekend.

**Comment by JahBrewski** [comment] 2015-06-30 16:21
@guylabs fantastic!

**Comment by guylabs** [comment] 2015-06-30 19:20
Hi you two,

I just added the functionality to the master. Could you please check it if it works and then write me such that I can close the issue?

Thanks and regards,

Guy

**Comment by JahBrewski** [comment] 2015-06-30 23:05
This is really close.. Only problem is when I first open the dialog the formatting is off:
![screen shot 2015-06-30 at 6 04 00 pm](https://cloud.githubusercontent.com/assets/2348386/8444072/852b8ab2-1f52-11e5-86cb-67bb91d66ab3.png)

**Comment by JahBrewski** [comment] 2015-06-30 23:29
Also, it would be nice if that list remained populated after clicking on an item. But maybe that's already a feature?

**Comment by taybin** [comment] 2015-07-01 02:06
I had the formatting problem too.  I fixed it locally by breaking out the function $watch('searchQuery') calls into its own named function and then calling that at the bottom of the onclick handler.

**Comment by guylabs** [comment] 2015-07-01 05:19
Ok I just fixed this issue too with the workaround that @taybin mentioned. Thanks for that!

@JahBrewski What do you mean that this list remains populated? That the list is never cleared if the query is an empty string? You mean to remove this part here right: https://github.com/guylabs/ion-autocomplete/blob/master/src/ion-autocomplete.js#L167 ?

**Comment by TimoSolo** [comment] 2015-07-01 08:44
Wonderful! I was just looking for this and saw you already updated the code :)
Works well. One little issue is that it calls the method twice (once when it loads the page and again when you click on the autocomplete field)

**Comment by guylabs** [comment] 2015-07-01 19:00
Hi Timothy,

well the problem is that Angular calls the `&watch` method at the beginning and with this change now to allow empty values it's not possible to just call the method when the real search input field is used. If anyone has an idea how to solve this then please tell me such that I can fix it or create a pull request.

Now for this issue: @taybin @JahBrewski I closed the issue now as @TimoSolo tested it but if there is an issue just reopen it.

Thanks and regards,

Guy

**Closed by guylabs** 2015-07-01 19:00 UTC
Labels: enhancement

**Comment by guylabs** [comment] 2015-07-02 05:42
Hi,

I just found out a way to not call the `items-method` for nothing: https://github.com/guylabs/ion-autocomplete/commit/5f9c56b7ec73fe53baa0d6f7c2d3eb7690b136bf. This also fixes some other places where the `items-method` was called because I set the `searchQuery` to an empty string. 

Now the `items-method` is just called if the component needs the data. This also improves the performance such that it doesn't make useless calls to the back end.

Regards,

Guy

**Comment by TimoSolo** [comment] 2015-07-02 06:47
Hmm.. that seems to break the initial list though.

I've got the code to work the way I want it: when you click on the ion-search it shows the full list. also when you select something it saves the search. I'll try create a pull request to demonstrate.

**Comment by TimoSolo** [comment] 2015-07-03 19:14
This still isn't working for me with the updates - it only shows the list if you start typing.. what do you think of the suggested pull request?
