### ISSUE TITLE
Populate autocomplete list after opening.

### ISSUE THREAD

**Issue by g0t00** [guylabs/ion-autocomplete#57] opened 2015-08-09 15:23 UTC
Hi,
I'm looking for a way to show some entries in the list, right after the user clicked on the autocomplete input field.
I want to use it like a filterable select.
Is there an option to activate this behaviour.
Thanks in advance :)

**Comment by guylabs** [comment] 2015-08-10 15:37
Hi,

do you want to show some already preselected items or just a list with some items such that the user doesn't need to enter some value into the input field? In the first case you are able to set the model with preselected values and implement the https://github.com/guylabs/ion-autocomplete#the-model-to-item-method.

Thanks and regards,

Guy

**Comment by g0t00** [comment] 2015-08-10 16:02
Hi Guy,

i already figured out the first case by looking at an example.
I'm asking about the second case.

Greetings,
Anton

**Comment by guylabs** [comment] 2015-08-13 05:11
Hi Anton,

would you want to set something like the listmodel which then shows these items right away in the list and then the user is still able to search in them right? Or is it a static list which is always the same?

Thanks and regards,

Guy

**Comment by tallented** [comment] 2015-08-21 21:17
Guy,

I solved this in my fork by adding an additional directive attribute that forces the items-method to be called even for the initial case where query === undefined.  This way I can always call my items method and have dynamic list options available.  

This allows me to workaround the commit "Do not call the items-method if not needed".

```
<ion-autocomplete ng-model="model" items-method="itemsMethod(query)" items-method-when-empty="true"/>
```

See https://github.com/Glamhive/ion-autocomplete/commit/d424e0533fb0c304c4d1e82299fac6e4c60c9701

**Comment by maurotrigo** [comment] 2015-08-25 00:21
Hi Guy,

I'm also looking to solve the second case. I would like to display maybe the results of an empty query (which in my case would return all of the elements), or perhaps a sample. It doesn't make a difference, I gathered that my users get a little bit confused when they see a blank list, but that they can filter afterwards.

Thanks,

Mauro

**Comment by guylabs** [comment] 2015-09-05 05:17
For reference: https://stackoverflow.com/questions/32250506/ion-autocomplete-show-alll-elements-before-userinput

**Comment by guylabs** [comment] 2015-09-08 22:02
Hi,

I finally got the time to add a solution. Please have a look at the master and at this documentation: https://github.com/guylabs/ion-autocomplete#search-items. There everything is described how to pre populate the search list.

Please tell me if that fixes your issue and then I can close this issue.

Thanks and regards,

Guy

**Comment by maurotrigo** [comment] 2015-09-11 21:10
Hi, I want to try the new version, but the latest release (0.3.1) is not available:

https://github.com/guylabs/ion-autocomplete/tree/v0.3.1

**Comment by guylabs** [comment] 2015-09-12 14:23
Hi,

you can use the master the following way: http://guylabs.ch/2015/05/08/get-latest-master-changes-of-a-bower-dependency/

If the issue is solved for you then I am able to release the 0.3.1 version when all other issues in this fix version are fixed too.

Thanks and regards,

Guy

**Comment by g0t00** [comment] 2015-09-12 14:56
Hi Guy,
following the guide on your homepage I managed to install the new version.
The function works, if you open the autocomplete window for the first time. 
If you select one item the list is empty again. Thats really inconsistent.

Also if you use ionic in browser there is a bug if you click on the autocomplete field and the window opens, that it automatically clicks on the appearing list entry, therefore selecting it instantly.
I don't know if its related to the new search-items parameter as the bug doesn't show if the list is empty (because you can't click on anything)

Greetings, 
Anton

**Comment by guylabs** [comment] 2015-09-17 20:12
Hi Anton,

well when you select an item the populated list will be cleared as then the user wants to enter a new value and all other autocomplete components that I know have the same functionality. If you do not want this behavior and always want the same list to be populated, then you are able to use a select component with a fixed list. 

And for the issue with the browser: I cannot reproduce this. What browser are you using and do you use the master of the `ion-autocomplete` component? Are you using a compatible Ionic version? Check here: https://github.com/guylabs/ion-autocomplete#ionic-compatibility

Thanks and regards,

Guy

**Comment by thedanielhanke** [comment] 2015-09-23 16:29
Hey @guylabs, thanks for your module, nice one! :+1: 

i jsut noticed that having this search-items attribute set, selecting an item clears the entire list. so i have to query e.g. '*' to get back the list. is that by intention?

Cheers

**Comment by g0t00** [comment] 2015-09-23 16:36
@thedanielhanke That's exactly my point. I think the expected behaviour would be, that for an empty input the result list should show the search-items array.

**Comment by guylabs** [comment] 2015-09-24 06:07
Hi,

@thedanielhanke thanks for the praise :smiley: 

it looks like this whole `search-items` feature is confusing. There was already the issue #38 and this pull request #42. Maybe I revert the `search-items` again and then you can fetch the list if the query is empty. This way you have the functionality you need such that when the query is empty a default list is shown and when the user enters a query you can filter them or not.

What do you two think about that?

Thanks and regards,

Guy

**Comment by g0t00** [comment] 2015-09-27 15:14
Yeah, that sounds great.

**Comment by nrcrabbe** [comment] 2015-10-02 03:39
Can I just add that the same behaviour is observed when `model-to-item-method` is used to set a default value. In this scenario the first time the user clicks the autocomplete field to reveal the search modal the list is blank. Any fix should include this scenario.

Thanks
Nathan

**Comment by thedanielhanke** [comment] 2015-10-05 13:21
@nrcrabbe can you check my PR if it fixes that issue as well? 
https://github.com/guylabs/ion-autocomplete/pull/82

**Comment by nrcrabbe** [comment] 2015-10-05 18:04
Hi @thedanielhanke.

I dropped in the code and it does not help in this scenario.

It did help in the scenario where the selected item is user selected. However I had a weird effect where the modal was only visible for a split second before disappearing again (on Chrome using ionic serve). What ever list item happens to be under the mouse is selected. I haven't looked into it very deeply though.

Ref: https://github.com/guylabs/ion-autocomplete/issues/80

**Comment by thedanielhanke** [comment] 2015-10-06 12:05
hehe, lucky you @nrcrabbe , my "quick investigation" took an hour of my life wasted :D on mobile device this does not happen. 

as soon as @guylabs is "back" (seems to be busy currently) i`d like to give back some more code - if he likes - then i`d also check your issue.

**Comment by guylabs** [comment] 2015-10-08 19:03
Hi @nrcrabbe, @thedanielhanke ,

sorry for my late response. Thanks for having a look at these issues and discussing about them. So here are my inputs on these issues:

* The `model-to-item-method` is used when you want to have the model prepopulated and not the search list when you open the modal. So this is another functionality and I think this is not related here, as this should work as expected. And if there is an issue with this, then could you @nrcrabbe please show me a reproducible codepen with the master?
* I think we need to discuss how we should implement the functionality of having a prepopulated search list. As I wrote here https://github.com/guylabs/ion-autocomplete/issues/57#issuecomment-142819933 I think I will revert this as part of version `0.3.2` such that you get an empty or null query to you `items-method` and then you could return the default values to prepopulate the list. What do you think about this? Then I would remove the `search-items` attribute and simplify the things again.

I do not want to implement something that you are not able to use in your projects so I am open to discuss about it.

Thanks and regards,

Guy

**Comment by nrcrabbe** [comment] 2015-10-08 21:22
Hi @guylabs.

first of all, thanks for your time and effort on this, and the same to others in the community.

I haven't read right the way back in the history of this and related issues, but I think I agree with what you wrote in the comment you referenced:

> This way you have the functionality you need such that when the query is empty a default list is shown and when the user enters a query you can filter them or not.

Speaking broadly, the functionality I would like is in pseudocode `if (!searchQuery) return all(searchItems);` This should apply regardless of whether the model has been pre-populated, populated by a prior user selection, or the model isn't populated.

I'll throw together a codePen sometime today.

Thanks
Nathan

**Comment by guylabs** [comment] 2015-10-09 05:02
Hi Nathan,

thanks for your reply and also your time and efforts! Ok cool then you have the same idea as I have. What about you @thedanielhanke ?

The plan is to finish off some other issues for `0.3.1`, then release `0.3.1` and then I will change this behavior in `0.3.2`.

Thanks and regards,

Guy

**Comment by thedanielhanke** [comment] 2015-10-09 05:03
@nrcrabbe Nathan, `if (!searchQuery) return all(searchItems);` - works using my PR like this:

```coffee

$scope.items = [
  { id: 1, name: "Item 1"}
  { id: 2, name: "Item 2"}
  { id: 3, name: "Item 3"}
] 
$scope.filter  = (query) -> $filter('filter')($scope.items, name: query)
```
in case you are unfamilar to coffeescript, `(x)->x()` is more or less equal to `(function(x) {return x();})`

and 
```html
        <input ion-autocomplete
               class="ion-autocomplete"
               autocomplete="off"
               item-value-key="id"
               item-view-value-key="name"
               items-method="filter(query)"
               search-items="items"
            />
```

if you cannot confirm, the codePen would be nice to see.

BR

**Comment by thedanielhanke** [comment] 2015-10-09 05:04
@guylabs oh, you where 1 second faster ;)

so "What about you @thedanielhanke ?"  - i am lost :) what is the actual question? 

did you see my PR btw?
BR

**Comment by guylabs** [comment] 2015-10-09 05:07
yep :smiley: .. well I want to discuss the second point in this comment https://github.com/guylabs/ion-autocomplete/issues/57#issuecomment-146655987. The thing about to remove the whole `search-items` property and just use the `items-method` for that.

And yes I saw your PR and thanks a lot for that but that fixes the current problem but it adds more complexity and most of the issues currently are about the `search-items` property. Therefore I want to simplify that again and release a version which removes all this complexity.

**Comment by thedanielhanke** [comment] 2015-10-09 05:12
ok gotcha.

what ever leads to simplification without dropping the feature itself seems more than legit to me
![thumbs]
(https://media.licdn.com/mpr/mpr/shrinknp_400_400/p/1/005/0b4/070/316fe8c.png)


if there is anything i can provide, please tell me ;)

**Comment by guylabs** [comment] 2015-10-09 05:14
ok great! Then lets have a look at the codepen of @nrcrabbe and then I come up with the change and you two can have a look at it and give feedback if you like. And hopefully then everything is clear and easy to use ;).

**Comment by nrcrabbe** [comment] 2015-10-09 05:31
@guylabs it has been a busy day and is past beer o'clock and is now kebab o'clock where I am. I'll sort you out something in the next 18 hours though.

**Comment by thedanielhanke** [comment] 2015-10-09 05:35
@guylabs ,this is a entirely different topic, but i want to apply to the refactorting thing

when i open a old template (= older than 15 minutes), i find myself confused by all these item*-attributes, which are named in a sense- and meaningful way in your docu.

example:
```
The model-to-item-method
This method is used if you want to prepopulate the model ....
``` 
-> `prepopulate-items` e.g.

just to mention ;)

BR

**Comment by guylabs** [comment] 2015-10-09 05:40
@thedanielhanke what do you mean by "old template" ? A custom template for the component?

Well the `model-to-item-method` attribute is used to define a function which converts the model value to the item value. Because you cannot show the model value if that differs from the view value (the search item). Do you know what I mean? So I cannot name it `prepopulate-items`.

**Comment by thedanielhanke** [comment] 2015-10-09 05:55
@guylabs sorry for beeing unclear. template: just any html-file i created a while ago, a form, a single input, anything i did accordingly to the documentation, then saved and closed for a while.

i see your point - naming is always a challenge. 
indeed, my example does not fit - the goal was to have something more intuitive.. 

however, its not a major concern, i just wanted to mention, since i had to re-read the docu after seeing the attributes.

**Comment by nrcrabbe** [comment] 2015-10-09 06:02
@thedanielhanke I'll have a look soonish.
@guylabs 0.3.2 would be great

**Comment by nrcrabbe** [comment] 2015-10-09 23:41
@guylabs  I've spent some time trying to get a codepen done and I'm getting unexpected results :/ I'm giving up now.

But I'm sure you have the right idea going by your comments. I agree with your analysis:

> I think we need to discuss how we should implement the functionality of having a prepopulated search list. As I wrote here #57 (comment) I think I will revert this as part of version 0.3.2 such that you get an empty or null query to you items-method and then you could return the default values to prepopulate the list. What do you think about this? Then I would remove the search-items attribute and simplify the things again.

That way the developer has the power of choosing what they do with the empty query. I'll be returning the complete unfiltered list. Someone else may decide `if(searchQuery == "") return []` is more appropriate for their use case.

**Comment by thedanielhanke** [comment] 2015-10-10 13:20
imo this should be done in the items-method, not inside the plugin at all.

**Comment by guylabs** [comment] 2015-11-04 19:14
Hi,

sorry for the delay but now I finished the things in the branch and could you please have a look at the documentation and test the new functionality on the branch and give me feedback asap? Then I am able to merge it to the master and then finally release `0.3.1`.

Now you are able to just use the `items-method` to do all the prepopulation and you are able to choose wether the search list gets cleared or not etc. Have a look at the new documentation of the `items-method`: https://github.com/guylabs/ion-autocomplete/tree/%2357-remove-search-items#the-items-method

Thanks and regards,

Guy

**Comment by nrcrabbe** [comment] 2015-11-06 04:08
@guylabs I have installed this branch and I am more than happy for you to merge into master.

Many thanks
Nathan

**Comment by guylabs** [comment] 2015-11-06 06:32
@nrcrabbe ok great! :) So what about you @thedanielhanke did you already have the time to test it? It would be nice if I can release `0.3.1.` next week to finally finish off this milestone ;).

**Comment by g0t00** [comment] 2015-11-11 13:17
@guylabs I'm sorry I didn't have the time to follow this closely. But I just checked out the newest version and i'm very happy with it now :)
Thanks a lot everyone.

**Comment by guylabs** [comment] 2015-11-11 13:39
@g0t00 ok nice :). @thedanielhanke did you have the time to look into it? If not then I will merge it to the master this week such that I can finally release `0.3.1`.

**Closed** 2015-11-17 20:19 UTC
Labels: question
