### ISSUE TITLE
selecting  an Item in predefined Items list clears list.

### ISSUE THREAD

**Issue by thedanielhanke** [guylabs/ion-autocomplete#80] opened 2015-09-23 16:38 UTC
Hi @guylabs 

it seems like the `preserveSearchItems` argument in `selectItem` call in your default-template is ignored, therefore the entire, when using searchItems-attribute prefilled, list gets cleared. 

in my case, i fixed it via:
```html
<ion-item collection-repeat="..."... ng-click="viewModel.selectItem(item, viewModel.preserveSearchItems)">
```

by defining `preserveSearchItems` like this:

```js
// the items, selected items and the query for the list
this.searchItems = valueOrDefault(this.searchItems, []);
this.preserveSearchItems = this.searchItems.length > 0;   // <- the workaround.
this.selectedItems = valueOrDefault(this.selectedItems, []);
```

i dont know what the intention is, which is why i dont create a pullrequest right now. Maybe its a Feature, not a Bug ;)

Cheers.

**Comment by guylabs** [comment] 2015-09-24 06:13
Hi Daniel,

yes that is definitely a bug. So if you still want to create a pull request it would be really appreciated! The problem is that currently I do not have much time for it and this would also right away fix #57.

Thanks and regards,

Guy

**Comment by thedanielhanke** [comment] 2015-09-24 06:54
will do, sure!

**Comment by guylabs** [comment] 2015-11-05 19:53
I will close this now as we have the #57 issue for this as there the functionality will change and then this issue would not be valid anymore.

**Closed by guylabs** 2015-11-05 19:53 UTC
Labels: duplicate
