### ISSUE TITLE
Only first item in the result list can be clicked

### ISSUE THREAD

**Issue by thim81** [guylabs/ion-autocomplete#47] opened 2015-07-06 22:13 UTC
Hi, 

I'm using your excellent autocomplete directive but for some reaon, I can only select/click on the first item in the result list?

```
<ion-autocomplete ng-model="parcel.pickup.address" placeholder="Enter your address ..." items-method="geoPlacesLookup(query)" item-view-value-key="description" items-clicked-method="clickedPlace(callback)"/>
```

I've written a custom Google Places AutocompleteService() which I call using the function geoPlacesLookup(query). This works perfectly but I can only click on the first item in the list.
The rest remains visible but not clickable?

Regards,
Tim

**Comment by thim81** [comment] 2015-07-06 22:14
Corrected a typo in the title

**Comment by guylabs** [comment] 2015-07-07 05:19
Hi Tim,

thanks for the praise ;). Do you need to have multiple selection? If yes please have a look here on how to achieve this: https://github.com/guylabs/ion-autocomplete#the-multiple-select. Which Ionic and ion-autocomplete version are you using? I just released 0.2.3 last Friday and maybe try it with this one.

And does it also happen with this template: https://github.com/guylabs/ion-autocomplete/blob/master/test/e2e/ion-autocomplete.single-select.e2e.html? It is hard to reproduce as I never had this issue, and maybe you are able to reproduce it somehow.

Thanks and regards,

Guy

**Comment by thim81** [comment] 2015-07-07 08:49
Hi Guy,

I'm using the latest ionic v1.0.1 and try to use a single select.
I have tried the single select from your template:

```
<label class="item item-input">
  <span class="input-label">Single select autocomplete</span>
  <ion-autocomplete ng-model="model"
                                  item-value-key="name"
                                  item-view-value-key="view"
                                  items-method="getTestItems(query)"
                                  items-method-value-key="items"
                                  placeholder="Enter test query ..."
                                  items-clicked-method="itemsClicked(callback)"
                                  component-id="comp1"/>
</label>
```

I have by the way an update, on the issue.
On a another screen have 2 elements on the screen, it seems that the ion-autocomplete items are clickable only when they are positioned above the form elements. 

![image](https://cloud.githubusercontent.com/assets/952446/8542362/6c485adc-2495-11e5-8c27-49c3bf621bd8.png)

The top 2 are clickable, but the rest not.
![image](https://cloud.githubusercontent.com/assets/952446/8542373/8346398e-2495-11e5-9f2b-0c25ea73aa92.png)

Do I need to set a height of the io-autocomplete items or am I missing something?

Regards,
Tim

**Comment by guylabs** [comment] 2015-07-24 10:46
Hi Tim, 

I had a look at this and changed some Ionic collection repeat height values but I couldn't reproduce it. Do you also have this issue when you use a standard Ionic collection repeat?

Thanks and regards,

Guy

**Comment by guylabs** [comment] 2015-08-13 05:07
Hi Tim,

I will close the issue now. If you have any news on this please reopen it.

Thanks and regards,

Guy

**Closed by guylabs** 2015-08-13 05:07 UTC
Labels: question
