### ISSUE TITLE
Search data not shown in the top of the list.

### ISSUE THREAD

**Issue by Neotrixsx** [guylabs/ion-autocomplete#225] opened 2017-03-14 11:17 UTC
I use
Ionic version: v1.3.2,
Plugin Version: 0.4.0

I use this Directive in my app. I face a problem that search data not shown in the top of the list. I try a lot, but not get success. Where I am typing "Facebook" but Facebook not come on top of the list. Please help

![screenshot_2017-03-14-16-44-16](https://cloud.githubusercontent.com/assets/7522102/23898192/28985a90-08d6-11e7-9fc3-b3be35f4a6b7.png)

**Comment by guylabs** [comment] 2017-03-14 13:00
HI @Neotrixsx 

well how does your `items-method` look like? The directive just shows the returned values of this method and you need to do the sorting in your `items-method` such that when the `query` parameter is `Facebook` that you also return the items array with `Facebook` as first entry such that is is shown as first entry in the drop down.

Thanks and regards

Guy

**Comment by Neotrixsx** [comment] 2017-03-15 05:38
In my Input section I use:
                          ` <input ion-autocomplete type="text"
                             readonly="readonly"
                             class="ion-autocomplete"
                             autocomplete="off"
                             ng-model="model"
                             item-value-key="id"
                             item-view-value-key="value"
                             items-method="callbackMethod(query, isInitializing)"
                             items-method-value-key="items"
                             placeholder="Enter test query ..."
                             items-clicked-method="itemsClicked(callback)"
                             max-selected-items="1"  />`

And **items-method look like**

` $scope.callbackMethod = function (query) {
            // depends on the configuration of the `items-method-value-key` (items) and the `item-value-key` (name) and `item-view-value-key` (name)
            return {
                items: [{
                        id: "1",
                        name: "chapmen",
                        view: "chapmen",
                    }, {
                        id: "2",
                        name: "black",
                        view: "black",
                    }, {
                        id: "3",
                        name: "facebook",
                        view: "facebook",
                    }, {
                        id: "4",
                        name: "facebook4",
                        view: "facebook4",
                    }, {
                        id: "5",
                        name: "facebook5",
                        view: "facebook6",
                    },
                       ]
            };
        };`

**Comment by guylabs** [comment] 2017-03-15 05:47
Hi @Neotrixsx 

well the problem is in the `items-method` as there you return a hard coded list of items in a specific order and this will then be displayed in the autocomplete. You do not do any filtering of these values based on the query. This is something you need to do by your own and you will surely find examples on the internet which show how to filter lists based on a query. (e.g. http://stackoverflow.com/questions/14302267/how-to-use-a-filter-in-a-controller)

So I will then close this issue as there is no problem with the directive itself but with your implementation of the `items-method`.

Thanks and regards,

Guy

**Closed by guylabs** 2017-03-15 05:47 UTC
Labels: question

**Comment by Neotrixsx** [comment] 2017-03-15 07:27
@guylabs if you can Please help me with this problem, and one more think is it possible if the user not found relevant data in dropdown so user add their own data, shown in home page [input ion-autocomplete] area and pass to the server. 

Please help me, I am new in ionic

**Comment by guylabs** [comment] 2017-03-16 11:35
Hi @Neotrixsx 

well as I said you need to implement your own logic in the `items-method`. Please ask in the official Ionic forum or at Stackoverflow for help as there you get the help needed.

I got barely time to fix the issues of the directive and I cannot give even more support for other topics/issues.

I hope you understand it.

Regards

Guy
