### ISSUE TITLE
Modal only displaying backdrop on 0.3.0, no contents

### ISSUE THREAD

**Issue by goneale** [guylabs/ion-autocomplete#74] opened 2015-09-14 12:27 UTC
Hi again Guy :)
I've just updated to the latest version 0.3.0 which, it seems according to 'dist' folder is the latest version in order to rectify issue #55 , I'm now receiving just a dim grey backdrop instead of my modal from which I can't click away from. If you recall, I'm using a custom template.
This is my setup migrated according to your release notes, do you spot any issues?
```html
<input ion-autocomplete type="text" readonly="readonly" class="ion-autocomplete" autocomplete="off"
   name="CustomerID" ng-model="model.CustomerID" item-value-key="ID" item-view-value-key="view.CustomerName" items-method="getCustomerQuery(query)"
   items-method-value-key="items" multiple-select="false" placeholder="" select-items-label="Select customer..." loading-icon="dots"
   items-clicked-method="customerClicked(callback)" template-url="templates/customer-select.html" ng-required="!isNewCustomer" />
```

Many thanks,
Graham

**Comment by guylabs** [comment] 2015-09-17 20:21
Hi Graham,

well if you are on the master you are able to remove the `multiple-select="false"` attribute and set the `maxSelectedItems`. But what kind of Ionic are you using? Did you check the https://github.com/guylabs/ion-autocomplete#ionic-compatibility paragraph? And please check your template with the one that is the default as there also some things are changed.

Thanks and regards,

Guy

**Comment by goneale** [comment] 2015-09-26 07:48
Hi Guy,

I've been upgrading ion-autocomplete today in order to hopefully resolve issue #55 for myself, I found I did indeed have to make quite a few changes to my template file (namely prefixing my ng specifics with `viewModel` for this to function) as you said.

Something else critical however, was the requirement of the custom templates to be wrapped at runtime with your randomising CSS div. Without this fix, this is precisely why we are receiving a backdrop only and no page contents. I am submitting a PR momentarily for you to look over.

Graham

**Comment by vko-online** [comment] 2015-09-30 07:30
In my case there is backdrop in front of actual ion-autocomplete modal. And you just cannot type anything, because of backdrop

**Comment by goneale** [comment] 2015-09-30 07:44
Yes @vko-online , it is because your template isn't rendering due to the randomised class name which appears to be new functionality.

**Comment by vko-online** [comment] 2015-09-30 08:48
Well, i'm not even using template, it's just plain demo from [codepen](http://codepen.io/guylabs/pen/GJmwMw?editors=101) which doesn't work in my case

**Comment by guylabs** [comment] 2015-10-08 18:52
Hi Graham,

we already had this issue in #70 and you can use the `{{viewModel.randomCssClass}}` in your template to get the random CSS class. This also worked for @katemihalikova. I hope that helps and you are able to do it this way.

Thanks a lot for the pull request #86 but I think it is cleaner if you use the  `{{viewModel.randomCssClass}}` in your template to set the proper CSS class. Then all the users are able to create a complete unique template and do not have a `<div>` wrapped around it. Or what do you think?

Thanks and sorry for the late response,

Guy

**Comment by guylabs** [comment] 2015-10-08 19:09
@vko-online I just had a look at your codepen and for me it works in chrome. With what browser did you test it?

**Comment by guylabs** [comment] 2015-10-13 13:46
Hi,

any news on this? I want to release `0.3.1` and I want to close this issue.

Thanks and regards,

Guy

**Comment by goneale** [comment] 2015-10-13 23:21
Sorry Guy, I'm really flat out with a project at the moment, but if you believe it should work and you've tested it, feel free to ignore my PR, I just didn't know any other way to approach it.

Cheers :)

**Comment by guylabs** [comment] 2015-10-14 16:16
Hi Graham,

well there were two developers which did it like I wrote in https://github.com/guylabs/ion-autocomplete/issues/74#issuecomment-146652629 and therefore it should work. But if there is still an issue please reopen the issue and write a comment.

Thanks and regards,

Guy

**Closed by guylabs** 2015-10-14 16:16 UTC
Labels: question

**Comment by amilino** [comment] 2016-05-10 12:05
If I manage control externally (manage-externally="true") then I also have a backdrop effect on show modal. If I enter view, open control modal first time, everything is ok. But if I after first time exit my view, reopen same view and open control modal. I only receive gray background.

**Comment by guylabs** [comment] 2016-05-14 12:00
Hi @amilino,

could you please provide a codepen with your exact configuration and a list of steps on how to reproduce it? Then I can have a look at it.

Thanks and regards,

Guy

**Comment by amilino** [comment] 2016-05-19 19:55
It's hard to isolate it in codepan. I recorded a video maybe you can have a look at it. I can also provide you with a link on my application if you can have a quick look. I managed to deploy it as a web application...

https://youtu.be/uIdNnOabif8

**Comment by amilino** [comment] 2016-05-23 11:35
Hi @guylabs,

I just realized that I must cleanup modal it is in some kind of conflict with autocomplete modal.

```
    // Cleanup the modal when we're done with it!
    $scope.$on('$destroy', function () {
        $scope.modal.remove();
    });
```

This fixed my issue!

Thnx.

**Comment by guylabs** [comment] 2016-06-21 16:06
Hi @amilino,

sorry for my late response. Ok nice that you could solve it. Can you maybe verify the following statement such that I can add this to the documentation:

> When you add the `ion-autocomplete` component to a separate Ionic modal then you need to remove the modal when you switch the view. You can achieve this by adding the following `destroy` listener where you will remove your separate modal:
```javascript
$scope.$on('$destroy', function () {
        $scope.modal.remove();
    });
```

Thanks and regards,

Guy

**Comment by amilino** [comment] 2016-06-22 06:08
Yes this's it. You can update your documentation.
