### ISSUE TITLE
Installing ion-autocomplete using ionic add results in duplicate ionic installation

### ISSUE THREAD

**Issue by gortok** [guylabs/ion-autocomplete#3] opened 2015-04-17 14:58 UTC
Problem:  Installing ion-autocomplete using `ionic add ion-autocomplete` results in a duplicate installation of ionic and its dependencies.

Steps to reproduce:

1. Create a new application: `ionic start myTestApp`.
2. `cd ./myTestApp`
3. `ionic add ion-autocomplete`

Note that it fails with the message:

> MacBook-Pro:app gjstocker$ ionic add ion-autocomplete
> Failed to find the bower component "ion-autocomplete".
> Are you sure it exists? (CLI v1.3.20)

4. `cd ./www` (going into www directory to see if we're able to install it there)
5. `ionic add ion-autocomplete`.  

The result of this process is that a duplicate `www` folder is created inside of the normal `www` folder with a copy installation of ionic and its dependencies.

Expected behavior: Installing the plugin using `ionic add ion-autocomplete` from the base app directory should work; and not result in a duplicate install of ionic `www`.

**Comment by guylabs** [comment] 2015-04-17 18:57
Hi George,

I found the issue why this is not working. The problem is that in the `0.1.2` version of ion-autocomplete the `bower.json` has a `dependencies` tag with a fixed ionic version. If you now use the newest ionic version (rc3) bower will generate a prompt which ionic version, angular version etc. to use. And this has the effect that this call [here](https://github.com/driftyco/ionic-cli/blob/32ea2a720c6f168085ad7dd9e89d2dcd62afdfc9/lib/ionic/add.js#L18) will not return a proper code and the `ionic add` task will fail.

I just tested it with the latest commit and now it works. Could you maybe test it with the following command and give me feedback?

```bash
ionic add 'git://github.com/guylabs/ion-autocomplete.git#98446e271a93756d70d176d2be510fa0058d2bd7'
```
The fix is to use the `devDependencies` of bower. Now one can use the component in all ionic versions, but the drawback is that you are not sure if it really works with the version you use. 

This will be fixed in the `0.2.0` release which I will release this Sunday. I hope this helps and fixes the issue.

Thanks and regards,

Guy

**Comment by gortok** [comment] 2015-04-17 19:21
This is awesome, Thanks!  I'm getting ready for a talk and wanted to use your autocomplete plugin for it. I'll let you know how it goes.

**Comment by guylabs** [comment] 2015-04-18 04:31
Ok cool! I'm keen on the feedback from you and the audience :). Ok then I will close this issue and then release 0.2.0 tomorrow. Is that ok for you?

**Closed** 2015-04-19 19:38 UTC
Labels: bug

**Comment by guylabs** [comment] 2015-05-19 12:50
Hi George,

did you already have the talk? Hope everything went fine :)

Regards,

Guy
