### ISSUE TITLE
How to wrap the selected values and make it look like tags input

### ISSUE THREAD

**Issue by nkiranrao** [guylabs/ion-autocomplete#114] opened 2015-11-14 17:09 UTC
I have have a list of items that user can select from, but unfortunately when the items are long, it does not wrap correctly and also looks hard to read inside the input.

`<input ion-autocomplete type="text" readonly="readonly" class="ion-autocomplete" autocomplete="off"
                               ng-model="registration.ShipperData.ProductsHandled"
                               item-value-key="ProductId"
                               item-view-value-key="ProductName"
                               items-method="getFilteredProducts(query)"
                               placeholder="touch here to select your products..."
                               items-clicked-method="itemsClicked(callback)"
                               items-removed-method="itemsRemoved(callback)"
                               max-selected-items="10"
                               />`

I also tried to change it to `textarea` that also do not look good. 

has anyone managed to make the selection look like tags?

**Comment by guylabs** [comment] 2015-11-17 19:06
Hi Kiran,

well currently the `textarea` is the only possibility. To have nice looking tags we would need to change the whole styling of the standard Ionic inputs and there are already ideas for that: http://forum.ionicframework.com/t/tag-input-like-in-ios-mail/5829. If you want you can come up with a PoC such that you could enable tagging support on the component. But currently there are no plans to support this in the near future.

Thanks for the idea and regards,

Guy

**Comment by guylabs** [comment] 2017-02-23 22:05
Closing as duplicate of #169.

**Closed by guylabs** 2017-02-23 22:05 UTC
Labels: enhancement
