### ISSUE TITLE
Need to trigger items-method Method Lookup on setting ng-model

### ISSUE THREAD

**Issue by flyer299** [guylabs/ion-autocomplete#119] opened 2015-11-28 05:39 UTC
I may be missing something in the document on how to do this.  But here is what I am trying to figure out.

I have the Auto Complete on a from that handles both Creating New Records and Updating existing Records.  I am using the Auto Complete to allow the User to select an Aircraft from a database controlled server side.

The Object Server Returns looks like:
{
  "Total": 2,
  "Data": [
    {
      "AircraftID": 1,
      "TailNumber": "N1234",
      "LastFlown": "2015-11-27T06:00:00",
      "TotalTime": 0
    },
    {
      "AircraftID": 116552,
      "TailNumber": "N46299",
      "Notes": null,
      "LastFlown": "2015-11-27T06:00:00",
      "TotalTime": 0.6
    }
  ]
}

So I've set the following attributes on the Directive:
                               ng-model="Flight.AircraftID"
                               item-value-key="AircraftID"
                               item-view-value-key="TailNumber"
                               items-method="SearchAircraft(query)"

Everything works great when I do not set a $scope.FlightAircraftID...
The user clicks...  Modal shows up, they type and get a list back.  They select the one they want...

The TailNumber Field is displayed to the user
The AircraftID is stored in the ng-model value.

I can save the record to the database.

But when I load an existing record.  I set the Flight.AircraftID to 116552.

What I want to see:
"N46299" displayed the end user

What I am seeing is:
116552

I am sure this is because AutoComplete doesn't know what to do with the number?   If it could fire a lookup event, I can translate it from the ID to the correct Display value.  But I can't figure out how to put that translation in there?

Any Suggestions?   This tool is fantastic, and if I can figure out this last piece, I will be using it proudly in my current project.

Thank you for your hardwork on this!

**Comment by guylabs** [comment] 2015-11-28 06:23
Hi,

thanks for the praise! :) I think the issue is that you did not implement/configure the `model-to-item-method` (https://github.com/guylabs/ion-autocomplete#the-model-to-item-method). This will do the lookup for the proper object such that the component is able to show the proper view value.

Can you please try that and give me feedback again?

Thanks and regards,

Guy

**Comment by flyer299** [comment] 2015-11-28 06:34
Thanks Guy,

I did try working with the model-to-item method and wasn't able to get it to work.  The documentation confused me a little bit.  

But now that you say that is the place to look for sure.  I will dig into more this weekend.  I am sure I can figure it out.  If you happen to have any additional sample code, it would be much appreciated.

If not, I am sure I will get it figured out.

This is my first project with Ionic and Cordova, so I am stumbling a little as I get used to the new frameworks.

**Comment by guylabs** [comment] 2015-11-28 06:53
Hi,

you can always have a look at this template here: https://github.com/guylabs/ion-autocomplete/blob/master/test/e2e/ion-autocomplete.prepopulated.e2e.html as this is using the exact same things as you need.

I hope you get it running.

Thanks and regards,

Guy

**Comment by flyer299** [comment] 2015-11-29 01:45
It looks like the model-to-item-method fires too early.   I know that I can return a Promise from that method and do the lookup that I want to do, but then I have to add an extra call to the server, which is a waste because I have all the data I need already in my other call to the server.  But that always fires after this method does.

I can make it work by adding the additional call, but can you think of any way around it?

The example you gave is very helpful.

**Comment by flyer299** [comment] 2015-11-29 02:45
I still couldn't get it to work.  I think it has to do with the fact that my Model is being returned by a Promise (remote server call).  And the Auto Complete is trying to initialize before that Promise is resolved.   So when my model is being set by the promise being resolved it doesn't run the look up again.  

Here are some Code Snippets from my project to try and illustrate.

```
<input ion-autocomplete
                               type="text"
                               readonly="readonly"
                               class="ion-autocomplete text-right"
                               autocomplete="off"
                               ng-model="Flight.AircraftIDb"
                               item-value-key="AircraftID"
                               item-view-value-key="TailNumber"
                               items-method="SearchAircraft(query)"
                               items-method-value-key="Data"
                               placeholder="Tap to Select..."
                               items-clicked-method="itemsClicked(callback)"
                               items-removed-method="itemsRemoved(callback)"
                               max-selected-items="1"
                               select-items-label="Select Aircraft"
                               external-model="defaultAircraft"
                               model-to-item-method="getDefaultAircraft(modelValue)" />
```


My Controller:
```
$scope.Flight.get({ Id: $scope.FlightID }, function (response) {
            var myAircraft = {
                AircraftID: response.AircraftID,
                TailNumber: response.TailNumber
            };
```
Flight.AircraftID is one of the Params that is returned from the service

'''
  $scope.SearchAircraft = function (query, isInitializing) {
        if (isInitializing == true) {
            alert('test');
        }
        if (query == "") {
            return $http.get(APIURL.url + "/api/AircraftKendo?{'take':10,'skip':0,'page':1,'pageSize':10}");
        } else {
            return $http.get(APIURL.url + "/api/AircraftKendo?{'take':10,'skip':0,'page':1,'pageSize':10, 'filter': {'logic':'and','filters':[{'value':'" + query + "','field':'TailNumber','operator':'startswith','ignoreCase':true}]}}");
        }
    };

    $scope.getDefaultAircraft = function (modelValue) {
        if ($scope.FlightID == 0) {
            $http.get(APIURL.url + "/api/DefaultAircraft/1/10");
        } else {
            $http.get(APIURL.url + "/api/DefaultAircraft/" + $scope.FlightID); 
        }
    };
'''

I may just have it display my own UI element at first displaying the data I have in my $scope.Flight object.   Then if they click to change it, it will switch to your directive (using ng-show trickery) and go from there.

I still feel like I am missing something simple.   I know it isn't your job to provide basic Angular support and I feel my troubles are more with getting angular working right than it is with your directive.   I still think your directive is working great.

Thank you for your help!

Ken

**Comment by guylabs** [comment] 2015-11-30 17:54
Hi Ken,

well inside the `getDefaultAircraft` method you need to return either a promise or an object of the item. Because in your current implementation you just call the back end withour returning anything. Well if you have the data for that already in the scope then you just need to extract it in the `getDefaultAircraft` method and return it.

Here you will see the code which gets executed when the `model-to-item-method` is called: https://github.com/guylabs/ion-autocomplete/blob/master/src/ion-autocomplete.js#L382

I would check the example again I showed you as this works as expected. Then I would modify/copy small parts to your application and always check that it is still working.

I can help you more if you could provide a running codepen which shows the issue.

Thanks and regards,

Guy

**Comment by flyer299** [comment] 2015-12-01 06:04
Thanks Guy, I put together a CodePen for you....   Hope it helps.  I pulled the parts out and made it work the same as it does in my application, but only put this once piece in.   

I added comments to help you see what I was thinking.   It calls my Live API to get the data.  It is tied to a Test Account, so you can't mess it up and the calls are all Read Only.

http://codepen.io/flyer299/pen/bVXzOJ

I've got my work around in place for now (not in the code pen).  But I would be interested in your thoughts on how to handle this.   

My next challenge is to handle if they type in a value that doesn't exist... I want to give them a Popup value to "Add" that value to the Database.  Adding a new value is a multiple step wizard they have to go through.   If you have any ideas, that would be helpful.  If not, I will play with it and figure something out.

Thank you again for all of your help.  Fingers crossed... Apple will be approving my Beta version of the app this week and we will have it in production.

**Comment by guylabs** [comment] 2015-12-08 06:53
Hi Ken,

I think the issue is with your `Flight` factory as this will be resolved separately and you do not return a promise in the `getDefaultAircraft` which can be resolved by the `ion-autocomplete` component. You could also wrap the call into a `$q` promise and then defer it in the response function of the `Flight` factory such that you can "call" when the `getDefaultAircraft` method is resolved. I do not see any other way of doing this.

Ok cool. Please keep me up to date about the state of the app and thanks for using this component!

Thanks and regards,

Guy

**Comment by guylabs** [comment] 2016-02-06 14:23
Hi,

due to inactivity I will close the issue. If you still have any issues or remarks please add a comment or reopen the issue.

Thanks and regards,

Guy

**Closed by guylabs** 2016-02-06 14:23 UTC
Labels: question
