### ISSUE TITLE
Allow user to type in selection

### ISSUE THREAD

**Issue by marcarausch** [guylabs/ion-autocomplete#75] opened 2015-09-15 10:21 UTC
Hi Guy

I have the autosuggest list populating as the user types, works beautifully, thank you. Is it possible for me to configure so that as the user types and the autosuggest list is populated, if the user wants type an option not in the list they can just hit the done button and the typed in value will be used, so they are not forced to use an item in the list?

**Comment by guylabs** [comment] 2015-09-15 15:43
Hi,

this issue is already handled here #48. It is not done the way you would like it but in a similar fashion such that the user is able to edit the input field or populate it with the model of available values.

I hope this helps. I will then close this as duplicate of #48.

If there is anything else don't hesitate to write a comment to this issue.

Thanks and regards,

Guy

**Closed by guylabs** 2015-09-15 15:43 UTC
Labels: question
