### ISSUE TITLE
Android hardware back button should trigger cancel-button-clicked-method callback

### ISSUE THREAD

**Issue by FakeHeal** [guylabs/ion-autocomplete#216] opened 2016-12-21 14:27 UTC
In my opinion the android back button should call the callback set for `cancel-button-clicked-method callback` , since it if I make some changes to already selected options and click on the back button those changes are accepted and the value of the autocomplete is changed.

**Comment by guylabs** [comment] 2017-01-28 17:13
Hi

I am sorry for the late response but I could not reply earlier.

Ok I see. So you mean to call the callback here: https://github.com/guylabs/ion-autocomplete/blob/master/src/ion-autocomplete.js#L307

Well maybe you can come up with a pull request? ;) As currently I do not have much time for the project.

Thanks and regards,

Guy

**Comment by guylabs** [comment] 2017-01-28 17:17
I will close it as duplicate of #212. Please write your comments there as someone already has a solution and maybe creates a pull request for it.

**Closed by guylabs** 2017-01-28 17:17 UTC
Labels: question
