### ISSUE TITLE
model-to-item-method not working

### ISSUE THREAD

**Issue by MazzMazz** [guylabs/ion-autocomplete#89] opened 2015-10-09 06:06 UTC
The ```model-to-item-method``` is working when i set the modelValue hardcoded. But i want that the user selects a country/city and gets the weatherInformation about it. 

So there is a list of weatherCodes: [1]:sunny,[2]:stormy etc. which i get from the backend. After i got the list i prepopulate the ```ion-autocomplete``` (works fine)

The user can now select a city and country. After selecting them i get the weatherCode of the selected city from the backend. If i get the weatherCode **1** i want that **sunny** is selected, if i get **2** i want that **stormy** is selected, but the ```model-to-item-method``` is not called when i change the model value. (the user can change the city as often as he wants)

If i got the weatherCode of the city from the backend it is saved like if i select an item manually
```$scope.form.weather.weatherCode = [20];```

Complete ion-autocomplete:
```javascript
<input ion-autocomplete
                               type="text"
                               readonly="readonly"
                               class="ion-autocomplete"
                               autocomplete="off"
                               model-to-item-method="modelToItemMethod(modelValue)"
                               max-selected-items="1"
                               ng-model="form.weather.weatherCode"
                               items-method="weatherAutocomplete(query)"
                               items-method-value-key="items"
                               item-value-key="id"
                               item-view-value-key="name"
                               component-id="weatherCode"
                               search-items="preload.weatherCode"
                               items-removed-method="resetPreload('weather')"
                                />
```
And my model-to-item-method
```javascript
$scope.modelToWeather = function(modelValue){
    return $scope.source.autocomplete.weatherCodes[modelValue];
/*    
Array is like this
$scope.source.autocomplete.weatherCodes[0] = "Tornado"
$scope.source.autocomplete.weatherCodes[1] =  "Tropischer Sturm"
$scope.source.autocomplete.weatherCodes[2] =  "Hurricane"
*/
};
```

**Comment by guylabs** [comment] 2015-10-13 05:51
Hi Mathias,

ok I finally got some time to work on it and could you maybe have a look at my last commit for this issue and check the https://github.com/guylabs/ion-autocomplete#external-model documentation and try it again? The `selected-items` attribute has been removed in favor of the `external-model`.

Thanks and regards,

Guy

**Comment by MazzMazz** [comment] 2015-10-17 13:06
Hey,
sorry for my late response.

Well i can see, that it is selected if i open the ion-autocomplete
<img width="321" alt="screen shot 2015-10-17 at 15 02 17" src="https://cloud.githubusercontent.com/assets/10706512/10558858/39890358-74e0-11e5-93a1-bd6e478e2063.png">

But from the outside it is not selected.
<img width="305" alt="screen shot 2015-10-17 at 15 02 22" src="https://cloud.githubusercontent.com/assets/10706512/10558859/3b6750a8-74e0-11e5-96a5-2ad57024d03f.png">

If i delete it and select it again it is like i want it.
<img width="301" alt="screen shot 2015-10-17 at 15 05 18" src="https://cloud.githubusercontent.com/assets/10706512/10558865/8b09f0ac-74e0-11e5-8ec7-d37d6dc81130.png">

**Comment by guylabs** [comment] 2015-10-18 04:43
Hi @MazzMazz,

could you maybe show me your setup in a CodePen? Do you use the `externalModel` to prepopulate/change the selected values?

Thanks and regards,

Guy

**Comment by MazzMazz** [comment] 2015-10-18 08:27
Well basically what I do is, put the value, which i get from the backend, in the externalModel (`source.weatherCodeTemp`). 

Then the model-to-item-method gets called. (Console output)
```
Model to Item method called
ModelValue: 28
Meist bewölkt (Tag)
```
but the Value of my `ng-model (form.weather.weatherCode)` is `[undefined]` after this procedure. Should be [28] as far as i know

I could setup a CodePen in the next few days if you really need it.

**Comment by MazzMazz** [comment] 2015-10-25 08:53
Sorry for being so late:
http://codepen.io/anon/pen/zvWKoo

Just click on the button to change the external model. If you then activate the ion-autocomplete you can see that the right one is selected, but from the outside it seems like nothing is selected.

**Comment by MazzMazz** [comment] 2015-11-05 14:36
Have you made any progress on this or could you tell me how to solve it? We really want to release our app

**Comment by guylabs** [comment] 2015-11-05 18:07
Hi Mathias,

I will have a look at it right now. Today I could finally do something on the component. I will try the codepen and see where the issue is.

Thanks for it and regards,

Guy

**Comment by guylabs** [comment] 2015-11-05 18:23
Hi Mathias,

I found the issue: you need to set the proper `item-value-key` and `item-view-value-key` and you also need to return a valid object in the `model-to-item-method`. This object needs to be the same as it would be when you return it in the `items-method`. The component itself uses the `item-value-key` and `item-view-value-key` to get the model and view value and these need to match to the object which is returned in the `model-to-item-method`.

Check out this working codepen: http://codepen.io/guylabs/pen/QjVroB

I hope that helps and can we then close this issue?

Thanks and regards,

Guy

**Comment by MazzMazz** [comment] 2015-11-05 19:16
Thank you very much, sorry was my fault. Yes can be closed.

**Comment by guylabs** [comment] 2015-11-05 19:30
Just for curiosity: in which app do you use the `ion-autocomplete` component? :smiley:

**Closed by guylabs** 2015-11-05 19:30 UTC
Labels: bug
